site_name: DeepTCR3
nav:
    - Home: index.md
    - API reference: api.md
    - Release History: releasehx.md
theme: readthedocs
plugins:
    - search
    - mkdocs-jupyter
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import sys
                    - sys.path.append('../')
                selection:
                    new_path_syntax: true
